extends:
  - pegasus
  - pegasus/typescript-recommended
  - pegasus/node

parserOptions:
  project: true

rules:
  no-invalid-this: off
  no-await-in-loop: off
  max-classes-per-file:
    - error
    - 2
