extends:
  - pegasus
  - pegasus/node

plugins:
  - '@babel'
  - jest

parser: '@babel/eslint-parser'

rules:
  'no-invalid-this': off
  '@babel/no-invalid-this': "error"

overrides:
  - files: 'scripts/*'
    rules:
      no-console: off

env:
  jest/globals: true
