extends:
  - pegasus
  - pegasus/node

plugins:
  - '@babel'
  - jest

parser: '@babel/eslint-parser'

rules:
  no-invalid-this: off
  no-await-in-loop: off
  '@babel/no-invalid-this': "error"
  max-classes-per-file:
    - error
    - 2
